In [1]:
import numpy as np

In [2]:
import pandas as pd

In [12]:
l = ["Apple","Mango","Orange","Banana"]

arr = np.array(["Pune","Purangabad","Nasik","Latur","Delhi"])

People = {"Name":"Harshal","Designation":"Student","City":"Pune"}

In [13]:
label = ["a","b","c","d"]
s1 = pd.Series(l,index=label)
s1

a     Apple
b     Mango
c    Orange
d    Banana
dtype: str

In [14]:
s1.iloc[3]

'Banana'

In [15]:
label = ["city1","city2","city3","city4","city5"]
s2 = pd.Series(arr,index=label)
s2

city1          Pune
city2    Purangabad
city3         Nasik
city4         Latur
city5         Delhi
dtype: str

In [16]:
s3 = pd.Series(People)
s3

Name           Harshal
Designation    Student
City              Pune
dtype: str

In [24]:
data = {
    "Name":["Harshal","Akshya","Shivani","Sakshi","Saurabh"],
    "age":[20,34,23,32,30],
    "City":["Pune","Jaipur","Solapur","Kolhapur","Pune"],
    "Salary":[10000,20000,30000,40000,50000]
}

data

{'Name': ['Harshal', 'Akshya', 'Shivani', 'Sakshi', 'Saurabh'],
 'age': [20, 34, 23, 32, 30],
 'City': ['Pune', 'Jaipur', 'Solapur', 'Kolhapur', 'Pune'],
 'Salary': [10000, 20000, 30000, 40000, 50000]}

In [25]:
label = ["A","B","C","D","E"]
df = pd.DataFrame(data,index=label)
df

      Name  age      City  Salary
A  Harshal   20      Pune   10000
B   Akshya   34    Jaipur   20000
C  Shivani   23   Solapur   30000
D   Sakshi   32  Kolhapur   40000
E  Saurabh   30      Pune   50000

In [32]:
df[["age","Name","Salary"]]

   age     Name  Salary
A   20  Harshal   10000
B   34   Akshya   20000
C   23  Shivani   30000
D   32   Sakshi   40000
E   30  Saurabh   50000

In [46]:
df["Designation"]= ["Student","Student","Dancer","Singer","Majdoor"]
df

      Name      City  Salary Designation
A  Harshal      Pune   10000     Student
B   Akshya    Jaipur   20000     Student
C  Shivani   Solapur   30000      Dancer
D   Sakshi  Kolhapur   40000      Singer
E  Saurabh      Pune   50000     Majdoor

In [48]:
#Drop Column
df["age"]=[20,34,23,32,30]
df.drop("age",axis=1,inplace=True)

In [51]:
df.iloc[[0,1]][["Salary","City"]]

   Salary    City
A   10000    Pune
B   20000  Jaipur

In [52]:
df.loc[["A","C"]]

      Name     City  Salary Designation
A  Harshal     Pune   10000     Student
C  Shivani  Solapur   30000      Dancer

In [54]:
df["age"]=[20,34,23,32,30]
df

      Name      City  Salary Designation  age
A  Harshal      Pune   10000     Student   20
B   Akshya    Jaipur   20000     Student   34
C  Shivani   Solapur   30000      Dancer   23
D   Sakshi  Kolhapur   40000      Singer   32
E  Saurabh      Pune   50000     Majdoor   30

In [57]:
df[df["age"]>30]

     Name      City  Salary Designation  age
B  Akshya    Jaipur   20000     Student   34
D  Sakshi  Kolhapur   40000      Singer   32

In [58]:
df[(df["age"]>30)&(df["City"]=="Jaipur")]

     Name    City  Salary Designation  age
B  Akshya  Jaipur   20000     Student   34

In [59]:
numbers = {
    "A" : [1,2,3,4,5],
    "B" : [1,np.nan,3,4,np.nan],
    "C" : [np.nan,56,3,np.nan,66],
    "D" : [np.nan,np.nan,3,np.nan,np.nan]
}

In [60]:
numbers

{'A': [1, 2, 3, 4, 5],
 'B': [1, nan, 3, 4, nan],
 'C': [nan, 56, 3, nan, 66],
 'D': [nan, nan, 3, nan, nan]}

In [63]:
df = pd.DataFrame(numbers)
df

   A    B     C    D
0  1  1.0   NaN  NaN
1  2  NaN  56.0  NaN
2  3  3.0   3.0  3.0
3  4  4.0   NaN  NaN
4  5  NaN  66.0  NaN

In [67]:
df.isna()

       A      B      C      D
0  False  False   True   True
1  False   True  False   True
2  False  False  False  False
3  False  False   True   True
4  False   True  False   True

In [68]:
df.isna().sum()

A    0
B    2
C    2
D    4
dtype: int64

In [69]:
df.isna().any()

A    False
B     True
C     True
D     True
dtype: bool

In [70]:
df

   A    B     C    D
0  1  1.0   NaN  NaN
1  2  NaN  56.0  NaN
2  3  3.0   3.0  3.0
3  4  4.0   NaN  NaN
4  5  NaN  66.0  NaN

In [71]:
df.dropna()

   A    B    C    D
2  3  3.0  3.0  3.0

In [74]:
df.dropna(thresh=2)

   A    B     C    D
0  1  1.0   NaN  NaN
1  2  NaN  56.0  NaN
2  3  3.0   3.0  3.0
3  4  4.0   NaN  NaN
4  5  NaN  66.0  NaN

In [75]:
df.fillna(0)

   A    B     C    D
0  1  1.0   0.0  0.0
1  2  0.0  56.0  0.0
2  3  3.0   3.0  3.0
3  4  4.0   0.0  0.0
4  5  0.0  66.0  0.0

In [76]:
df.fillna(df.mean())

   A         B          C    D
0  1  1.000000  41.666667  3.0
1  2  2.666667  56.000000  3.0
2  3  3.000000   3.000000  3.0
3  4  4.000000  41.666667  3.0
4  5  2.666667  66.000000  3.0